USE MASTER
IF EXISTS (SELECT * FROM sys.databases WHERE name = 'Inicio_Sesion')
BEGIN
  ALTER DATABASE Inicio_Sesion SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
  DROP DATABASE Inicio_Sesion;
END
CREATE DATABASE Inicio_Sesion
GO
USE Inicio_Sesion

CREATE TABLE CARGO
(
ID INT IDENTITY(1,1) PRIMARY KEY, 
NOMBRE VARCHAR(50) NOT NULL
)

CREATE TABLE USUARIO
(
ID INT IDENTITY(1,1) PRIMARY KEY, 
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
NOMBRE_USUARIO VARCHAR(50) UNIQUE NOT NULL,
PASSWORD_USUARIO VARCHAR(50) NOT NULL,
ID_CARGO INT CONSTRAINT FK_Cargo FOREIGN KEY(ID_CARGO) REFERENCES CARGO(ID)
)
GO
INSERT INTO CARGO VALUES ('Jefe')
INSERT INTO CARGO VALUES ('Administrador')
INSERT INTO CARGO VALUES ('Empleado')
GO

GO
INSERT INTO USUARIO VALUES ('Roberto','Gómez','Roberto','r123456',1)
INSERT INTO USUARIO VALUES ('Pablo','Martínez','Pablo','p123456',2)
INSERT INTO USUARIO VALUES ('Edgar','Zambrano','Edgar','e123456',3)
GO

/*SELECT U.NOMBRE,U.APELLIDO,U.NOMBRE_USUARIO,U.PASSWORD_USUARIO,C.NOMBRE FROM USUARIO U INNER JOIN CARGO C ON U.ID_CARGO=C.ID WHERE NOMBRE_USUARIO=@nombreUsuario AND PASSWORD_USUARIO COLLATE Latin1_General_CS_AS=@contrasena
SELECT * FROM USUARIO U INNER JOIN CARGO C ON U.ID_CARGO=C.ID WHERE NOMBRE_USUARIO='Roberto' AND PASSWORD_USUARIO COLLATE Latin1_General_CS_AS='r123456'

select *from usuario

UPDATE USUARIO SET PASSWORD_USUARIO = @nuevaContrasena WHERE NOMBRE_USUARIO=@usuario

SELECT NOMBRE FROM CARGO*/

/*INSERT INTO USUARIO VALUES (@nombre,@apellido,@nombreUsuario,@contrasena,@cargo)

select * from USUARIO

SELECT ID FROM CARGO WHERE NOMBRE=@nombreCargo*/